name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.16
      
    steps:
    - name: Install raylib
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:texus/raylib
        sudo apt-get update
        sudo apt-get install -y libraylib5-dev
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run build
      run: shards build
