name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.16-alpine

    steps:
    - name: Install raylib
      run: |
        apk update
        apk add raylib --no-cache
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run build
      run: shards build
