permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.16
      
    steps:
    - name: Install raylib
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:texus/raylib
        apt-get update
        apt-get install -y libraylib5-dev
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run build
      run: shards build
    - name: Upload binaries to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/hello-raylib"
        body: "Please enjoy new release"
        allowUpdates: true
